# -*- coding: utf-8 -*-
"""01_data_preparation_json.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9Cp-DMcAlIjGwuw61fA6JWV6L_5VHTJ
"""

!pip install unidecode

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import unidecode
import re
import requests
import os
import zipfile

from pathlib import Path

from sklearn.ensemble import IsolationForest

from google.colab import drive
drive.mount('/content/drive')

"""**NETTOYAGE**"""

# ID du dataset DVF sur data.gouv.fr
DATASET_ID = "5c4ae55a634f4117716d5656"


def download_all_dvf_files(output_dir="dvf_data", force_redownload=False):
    """
    Télécharge et décompresse tous les fichiers DVF disponibles

    Args:
        output_dir: dossier de destination
        force_redownload: re-télécharger même si les fichiers existent

    Returns:
        Dictionnaire {année: filepath}
    """
    Path(output_dir).mkdir(exist_ok=True)

    api_url = f"https://www.data.gouv.fr/api/1/datasets/{DATASET_ID}/"
    response = requests.get(api_url)

    if response.status_code != 200:
        print(f"Erreur API: {response.status_code}")
        return {}

    dataset = response.json()
    downloaded_files = {}

    print(f"Dataset: {dataset['title']}\n")

    for resource in dataset['resources']:
        title = resource.get('title', '')
        url = resource.get('url', '')
        format_type = resource.get('format', '').lower()

        # Extraire l'année
        year_match = re.search(r'20\d{2}', title)
        if not year_match:
            continue

        year = year_match.group()

        # Gérer les fichiers TXT et ZIP
        if 'txt' in format_type or 'zip' in format_type:
            filename = f"dvf_{year}.txt"
            filepath = os.path.join(output_dir, filename)

            # Vérifier si déjà téléchargé
            if os.path.exists(filepath) and not force_redownload:
                file_size = os.path.getsize(filepath) / (1024 * 1024)
                if file_size > 1:  # Au moins 1 MB
                    print(f"⏭  {filename} existe déjà ({file_size:.2f} MB)")
                    downloaded_files[year] = filepath
                    continue

            try:
                print(f"Téléchargement: {title}")
                file_response = requests.get(url, stream=True, timeout=180)

                if file_response.status_code != 200:
                    print(f"  ✗ Erreur HTTP {file_response.status_code}\n")
                    continue

                # Sauvegarder temporairement
                temp_file = os.path.join(output_dir, f"temp_{year}")
                with open(temp_file, 'wb') as f:
                    for chunk in file_response.iter_content(chunk_size=8192):
                        f.write(chunk)

                # Si c'est un ZIP, décompresser
                if zipfile.is_zipfile(temp_file):
                    print(f"  Décompression du ZIP...")
                    with zipfile.ZipFile(temp_file, 'r') as zip_ref:
                        txt_files = [f for f in zip_ref.namelist() if f.endswith('.txt')]
                        if txt_files:
                            zip_ref.extract(txt_files[0], output_dir)
                            extracted = os.path.join(output_dir, txt_files[0])
                            os.rename(extracted, filepath)
                    os.remove(temp_file)
                else:
                    os.rename(temp_file, filepath)

                file_size = os.path.getsize(filepath) / (1024 * 1024)
                print(f"  ✓ {filename} prêt ({file_size:.2f} MB)\n")
                downloaded_files[year] = filepath

            except Exception as e:
                print(f"  ✗ Erreur: {e}\n")
                if os.path.exists(temp_file):
                    os.remove(temp_file)

    print(f"{'='*60}")
    print(f"Résumé: {len(downloaded_files)} fichiers téléchargés")
    print(f"Années: {sorted(downloaded_files.keys(), reverse=True)}")
    print(f"{'='*60}\n")

    return downloaded_files


def load_dvf_by_chunks(filepath, chunksize=50000):
    """
    Charge un fichier DVF par morceaux

    Args:
        filepath: chemin vers le fichier
        chunksize: nombre de lignes par chunk

    Returns:
        DataFrame complet
    """
    print(f"Chargement de {filepath}...")

    chunks = []
    total_rows = 0

    try:
        for i, chunk in enumerate(pd.read_csv(
            filepath,
            sep='|',
            encoding='latin-1',
            chunksize=chunksize,
            on_bad_lines='skip',
            engine='python'
        )):
            chunks.append(chunk)
            total_rows += len(chunk)
            if (i + 1) % 10 == 0:
                print(f"  Chunk {i+1}: {total_rows:,} lignes chargées...")

        df = pd.concat(chunks, ignore_index=True)
        df.columns = df.columns.str.strip()

        print(f"✓ {len(df):,} lignes chargées au total")
        print(f"✓ {len(df.columns)} colonnes\n")

        return df

    except Exception as e:
        print(f"✗ Erreur: {e}\n")
        return None


def run_dvf_pipeline(
    years=None,
    output_dir="dvf_data",
    force_redownload=False
):
    """
    Pipeline complet DVF : téléchargement + chargement complet

    Args:
        years: liste d'années à traiter, ex: ['2023', '2024']
               None = toutes les années disponibles
        output_dir: dossier de destination
        force_redownload: re-télécharger même si fichiers existants

    Returns:
        Dictionnaire {année: DataFrame}
    """

    # ── 1. Téléchargement ─────────────────────────────────────────
    print("=== ÉTAPE 1 : Téléchargement ===")
    downloaded = download_all_dvf_files(
        output_dir=output_dir,
        force_redownload=force_redownload
    )

    if not downloaded:
        print("Aucun fichier téléchargé. Abandon.")
        return {}

    # Filtrer sur les années demandées
    if years is not None:
        years = [str(y) for y in years]
        downloaded = {y: p for y, p in downloaded.items() if y in years}
        missing = set(years) - set(downloaded.keys())
        if missing:
            print(f"⚠ Années introuvables : {sorted(missing)}")

    # ── 2. Chargement complet ─────────────────────────────────────
    print("\n=== ÉTAPE 2 : Chargement ===")
    dfs = {}

    for year, filepath in sorted(downloaded.items(), reverse=True):
        print(f"\n── Année {year} ──")
        df = load_dvf_by_chunks(filepath)

        if df is not None and len(df) > 0:
            dfs[year] = df

    if not dfs:
        print("Aucune donnée chargée. Abandon.")
        return {}

    # ── 3. Injection dans le namespace global ─────────────────────
    for year, df in dfs.items():
        globals()[f"df_{year}"] = df

    print(f"\n{'='*50}")
    print(f"✓ Pipeline terminé — {len(dfs)} année(s) chargée(s) : "
          f"{sorted(dfs.keys(), reverse=True)}")
    print(f"✓ Variables créées : "
          f"{['df_' + y for y in sorted(dfs.keys(), reverse=True)]}")

    return dfs

# ── Lancement ─────────────────────────────────────────────────────
dfs = run_dvf_pipeline()

def nettoyage(df):
    df = df[df['Nature mutation'] == 'Vente']
    df = df[['Date mutation', 'Valeur fonciere', 'Code postal', 'Commune', 'Code departement', 'Code type local', 'Surface reelle bati', 'Surface terrain']]
    df = df.dropna(subset=['Valeur fonciere', 'Code postal', 'Code type local', 'Surface reelle bati']).reset_index(drop=True)
    df = df.drop_duplicates()
    df = df[df['Code type local'].isin([1, 2])]

    df['Date mutation'] = pd.to_datetime(df['Date mutation'], format='%d/%m/%Y', errors='coerce')
    df['Année'] = df['Date mutation'].dt.year
    df['Valeur fonciere'] = df['Valeur fonciere'].astype(str).str.replace(',', '.').str.replace(r'\s+', '', regex=True).astype(float).round().astype(int)
    df['Surface reelle bati'] = df['Surface reelle bati'].astype(int)
    df['Surface terrain'] = df['Surface terrain'].fillna(0).astype(int)
    df['Code type local'] = df['Code type local'].astype(int)
    df.drop(columns=['Date mutation'], inplace=True)

    # Filtres prix et surface minimum
    df = df[(df['Valeur fonciere'] >= 30000) & (df['Surface reelle bati'] >= 15)]

    numeric_df = df[['Valeur fonciere', 'Surface reelle bati', 'Surface terrain']]

    iso_forest = IsolationForest(contamination=0.15, random_state=42)
    predictions = iso_forest.fit_predict(numeric_df)

    df['anomaly'] = predictions
    df_clean = df[predictions == 1]
    df_clean = df_clean.drop(columns=['anomaly'])
    df_clean = df_clean.reset_index(drop=True)

    return df_clean

df_list = []
for year in sorted(dfs.keys(), reverse=True):
    df_list.append(nettoyage(dfs[year]))

df_final = pd.concat(df_list, axis=0, ignore_index=True)

df_final['Code departement'].unique()

df_final.to_csv('/content/drive/MyDrive/Use Case/Projet 3/df_final.csv', index=False)

"""**FEATURING ENGINEERING**"""

df = pd.read_csv('/content/drive/MyDrive/Use Case/Projet 3/df_par_ventes.csv')

# Sur data.gouv, les données commencent qu'à partir de 2022. J'ai donc pris les données de 2022 pour 2020 et 2021
df_commune_22 = pd.read_csv('/content/drive/MyDrive/Use Case/Projet 2/Data/communes-france-2022.csv', sep=',', low_memory=False)
df_commune_23 = pd.read_csv('/content/drive/MyDrive/Use Case/Projet 2/Data/communes-france-2023.csv', sep=',', low_memory=False)
df_commune_24 = pd.read_csv('/content/drive/MyDrive/Use Case/Projet 2/Data/communes-france-2024.csv', sep=',', low_memory=False)

df_commune_22["annee"] = 2022
df_commune_23["annee"] = 2023
df_commune_24["annee"] = 2024

df_commune = pd.concat([df_commune_22, df_commune_23, df_commune_24], axis=0)

def normaliser_nom(nom):
    if pd.isna(nom):
        return nom

    nom_normalise = str(nom).upper() # 1. Passage en majuscules
    nom_normalise = nom_normalise.replace('-', ' ').replace("'", ' ')
    nom_normalise = re.sub(r'\bST\s', 'SAINT ', nom_normalise)
    nom_normalise = re.sub(r'\bSTe\s', 'SAINTE ', nom_normalise)
    nom_normalise = unidecode.unidecode(nom_normalise) # 2. Suppression des accents
    nom_normalise = re.sub(r'\([^)]*\)', '', nom_normalise) # 3. Suppression des parenthèses

    match_chiffre = re.search(r'\d', nom_normalise)
    if match_chiffre:
        index_chiffre = match_chiffre.start()
        nom_normalise = nom_normalise[:index_chiffre]

    nom_normalise = ' '.join(nom_normalise.split()) # Supprimer les espaces multiples

    return nom_normalise

def prep_annee(df) :
    df['annee_pop'] = np.where(
        (df["Année"] == 2020) | (df["Année"] == 2021),
        2022,
        df["Année"]
    )
    return df

def normaliser_nom_avec_arrondissement(nom, code_dept=None):

    nom_norm = nom.upper().strip()

    # Pattern pour détecter les arrondissements avec "ARRONDISSEMENT"
    # Ex: "PARIS 13E ARRONDISSEMENT" ou "PARIS 1ER ARRONDISSEMENT"
    pattern_long = r'^(PARIS|LYON|MARSEILLE)\s+(\d+)(?:ER|E|EME)?\s+ARRONDISSEMENT'
    match_long = re.match(pattern_long, nom_norm)

    if match_long:
        ville = match_long.group(1)
        numero = match_long.group(2).zfill(2)
        return f"{ville} {numero}"

    # Pattern pour détecter le format court avec suffixe
    # Ex: "PARIS 13", "LYON 2EME", "MARSEILLE 1ER"
    pattern_court = r'^(PARIS|LYON|MARSEILLE)\s+(\d+)(?:ER|E|EME)?$'
    match_court = re.match(pattern_court, nom_norm)

    if match_court:
        ville = match_court.group(1)
        numero = match_court.group(2).zfill(2)
        return f"{ville} {numero}"

    return normaliser_nom(nom)


def merge_population(df_commune, df):
    # Supprimer les colonnes qui vont être remplacées
    df = df.drop(columns=['Nb_hab_com', 'Dens_hab_com', 'latitude_mairie', 'longitude_mairie'], errors='ignore')

    df_commune_prep = df_commune.copy()

    # Créer la clé avec nom normalisé + année + département
    df_commune_prep['Cle_Commune'] = (
        df_commune_prep.apply(
            lambda row: normaliser_nom_avec_arrondissement(row['nom_standard_majuscule'], row['dep_code']),
            axis=1
        ) + '_' +
        df_commune_prep['annee'].astype(str) + '_' +
        df_commune_prep['dep_code'].astype(str)
    )

    df_commune_pop = df_commune_prep[['Cle_Commune', 'population', 'latitude_mairie', 'longitude_mairie']].drop_duplicates(subset=['Cle_Commune'])
    df_prep = prep_annee(df)

    # Créer la clé avec nom normalisé + année + département
    df_prep['Cle_Commune'] = (
        df_prep.apply(
            lambda row: normaliser_nom_avec_arrondissement(row['Commune'], row['Code departement']),
            axis=1
        ) + '_' +
        df_prep['annee_pop'].astype(str) + '_' +
        df_prep['Code departement'].astype(str)
    )

    df = pd.merge(
        df_prep,
        df_commune_pop,
        on='Cle_Commune',
        how='inner'
    )

    df = df.rename(columns={'population': 'Nb_hab_com'})
    df = df.drop(['annee_pop', 'Cle_Commune'], axis=1)
    df = df[df['Nb_hab_com'] > 0]
    df['Commune'] = df['Commune'].astype('category')
    df['Code departement'] = df['Code departement'].astype('category')
    df['Code postal'] = df['Code postal'].astype('category')

    return df

df = merge_population(df_commune, df)

df.info()

df

df.to_csv('/content/drive/MyDrive/Use Case/Projet 3/df_par_ventes2.csv', index=False)

"""**BASE PAR VILLE**"""

import pandas as pd
import numpy as np
import json

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Use Case/Projet 3/df_par_vente.csv')

df.columns

import torch
print(torch.cuda.is_available())  # True si GPU activé
print(torch.cuda.get_device_name(0))  # ex: "Tesla T4"

df = df[df['Surface reelle bati'] > 0].copy()
df['Prix_m2'] = (df['Valeur fonciere'] / df['Surface reelle bati']).round(2)

df_agg = df.rename(columns={
    'Valeur fonciere': 'Valeur_fonciere',
    'Surface reelle bati': 'Surface_reelle_bati',
    'Surface terrain': 'Surface_terrain',
    'Code type local': 'Code_type_local',
    'Année': 'Annee'
})

# 3) Normalisation des noms de communes : PARIS/LYON/MARSEILLE arrondissements -> "PARIS 01", "LYON 08", "MARSEILLE 10"
def normalise_commune_arrondissement(nom, code_dept=None):
    nom_norm = str(nom).upper().strip()
    # Arrondissements avec "ARRONDISSEMENT"
    m = re.match(r'^(PARIS|LYON|MARSEILLE)\s+(\d+)(?:ER|E|EME)?\s+ARRONDISSEMENT', nom_norm)
    if m:
        return f"{m.group(1)} {m.group(2).zfill(2)}"
    # Format court : "PARIS 13", "LYON 2EME", "MARSEILLE 1ER"
    m = re.match(r'^(PARIS|LYON|MARSEILLE)\s+(\d+)(?:ER|E|EME)?$', nom_norm)
    if m:
        return f"{m.group(1)} {m.group(2).zfill(2)}"
    return nom_norm

df_agg['Commune_norm'] = df_agg.apply(lambda r: normalise_commune_arrondissement(r['Commune'], r['Code departement']), axis=1)

# Réduire la mémoire : ne garder que les colonnes utilisées (groupby + remplir_stats + pop/dens/coords)
cols_keep = ['Commune_norm', 'Code departement', 'Annee', 'Code_type_local', 'Valeur_fonciere', 'Surface_reelle_bati', 'Surface_terrain', 'Prix_m2']
for c in ['Nb_hab_com', 'latitude_mairie', 'longitude_mairie']:
    if c in df_agg.columns:
        cols_keep.append(c)
df_agg = df_agg[cols_keep].copy()
df_agg['Commune_norm'] = df_agg['Commune_norm'].astype('category')
df_agg['Code departement'] = df_agg['Code departement'].astype(str).astype('category')

# 4) Construction du dictionnaire : (Commune_norm, Code departement) -> { variable: { année: valeur } }
VARIABLES_JSON = [
    'Nb_total_ventes', 'Nb_ventes_maisons', 'Nb_ventes_appartements',
    'Prix_moy', 'Prix_med', 'Prix_min', 'Prix_max', 'Ecart_type_prix',
    'Prix_m2_moy', 'Prix_m2_med', 'Prix_m2_min', 'Prix_m2_max',
    'Surface_moy_interieur', 'Surface_med_interieur', 'Surface_moy_terrain', 'Surface_med_terrain',
    'Prix_moy_maison', 'Prix_med_maison', 'Prix_m2_moy_maison', 'Prix_m2_med_maison',
    'Surface_moy_maison', 'Terrain_moy_maison',
    'Prix_moy_appartement', 'Prix_med_appartement',
    'Prix_m2_moy_appartement', 'Prix_m2_med_appartement', 'Surface_moy_appartement'
]

dico = {}

def safe_float(x):
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return None
    return round(float(x), 2) if isinstance(x, (int, float)) else x

def remplir_stats(dico_key, g, m, a, year_str):
    dico_key['Nb_total_ventes'][year_str] = len(g)
    dico_key['Nb_ventes_maisons'][year_str] = len(m)
    dico_key['Nb_ventes_appartements'][year_str] = len(a)
    dico_key['Prix_moy'][year_str] = safe_float(g['Valeur_fonciere'].mean())
    dico_key['Prix_med'][year_str] = safe_float(g['Valeur_fonciere'].median())
    dico_key['Prix_min'][year_str] = safe_float(g['Valeur_fonciere'].min())
    dico_key['Prix_max'][year_str] = safe_float(g['Valeur_fonciere'].max())
    dico_key['Ecart_type_prix'][year_str] = safe_float(g['Valeur_fonciere'].std())
    dico_key['Prix_m2_moy'][year_str] = safe_float(g['Prix_m2'].mean())
    dico_key['Prix_m2_med'][year_str] = safe_float(g['Prix_m2'].median())
    dico_key['Prix_m2_min'][year_str] = safe_float(g['Prix_m2'].min())
    dico_key['Prix_m2_max'][year_str] = safe_float(g['Prix_m2'].max())
    dico_key['Surface_moy_interieur'][year_str] = safe_float(g['Surface_reelle_bati'].mean())
    dico_key['Surface_med_interieur'][year_str] = safe_float(g['Surface_reelle_bati'].median())
    dico_key['Surface_moy_terrain'][year_str] = safe_float(g['Surface_terrain'].mean())
    dico_key['Surface_med_terrain'][year_str] = safe_float(g['Surface_terrain'].median())
    dico_key['Prix_moy_maison'][year_str] = safe_float(m['Valeur_fonciere'].mean()) if len(m) else None
    dico_key['Prix_med_maison'][year_str] = safe_float(m['Valeur_fonciere'].median()) if len(m) else None
    dico_key['Prix_m2_moy_maison'][year_str] = safe_float(m['Prix_m2'].mean()) if len(m) else None
    dico_key['Prix_m2_med_maison'][year_str] = safe_float(m['Prix_m2'].median()) if len(m) else None
    dico_key['Surface_moy_maison'][year_str] = safe_float(m['Surface_reelle_bati'].mean()) if len(m) else None
    dico_key['Terrain_moy_maison'][year_str] = safe_float(m['Surface_terrain'].mean()) if len(m) else None
    dico_key['Prix_moy_appartement'][year_str] = safe_float(a['Valeur_fonciere'].mean()) if len(a) else None
    dico_key['Prix_med_appartement'][year_str] = safe_float(a['Valeur_fonciere'].median()) if len(a) else None
    dico_key['Prix_m2_moy_appartement'][year_str] = safe_float(a['Prix_m2'].mean()) if len(a) else None
    dico_key['Prix_m2_med_appartement'][year_str] = safe_float(a['Prix_m2'].median()) if len(a) else None
    dico_key['Surface_moy_appartement'][year_str] = safe_float(a['Surface_reelle_bati'].mean()) if len(a) else None

for (commune_norm, dep), group in df_agg.groupby(['Commune_norm', 'Code departement']):
    dep_str = str(dep).strip() if dep is not None else str(dep)
    key = (str(commune_norm).strip(), dep_str)
    dico[key] = {var: {} for var in VARIABLES_JSON}
    dico[key]['population'] = {}  # population par année (Nb_hab_com)
    dico[key]['coordonnees'] = None  # une seule valeur (invariant par année)

    for annee in sorted(group['Annee'].dropna().unique()):
        g = group[group['Annee'] == annee]
        m = g[g['Code_type_local'] == 1]   # maisons
        a = g[g['Code_type_local'] == 2]   # appartements
        year_str = str(int(annee))
        remplir_stats(dico[key], g, m, a, year_str)
        if 'Nb_hab_com' in g.columns and len(g) > 0 and g['Nb_hab_com'].notna().any():
            val = g['Nb_hab_com'].iloc[0]
            dico[key]['population'][year_str] = int(val) if pd.notna(val) else None
        else:
            dico[key]['population'][year_str] = None
        # Coordonnées : une seule valeur (identique toutes années)
        if dico[key]['coordonnees'] is None:
            lat = safe_float(g['latitude_mairie'].iloc[0]) if 'latitude_mairie' in g.columns and len(g) > 0 and g['latitude_mairie'].notna().any() else None
            lon = safe_float(g['longitude_mairie'].iloc[0]) if 'longitude_mairie' in g.columns and len(g) > 0 and g['longitude_mairie'].notna().any() else None
            dico[key]['coordonnees'] = { 'latitude_mairie': lat, 'longitude_mairie': lon }

# 5) Ajout des agrégats PARIS, LYON, MARSEILLE (ville entière = tous arrondissements)
agg_ville_dep = [('PARIS', '75'), ('LYON', '69'), ('MARSEILLE', '13')]
for ville_glob, dep_str in agg_ville_dep:
    mask = (df_agg['Code departement'].astype(str) == dep_str) & (df_agg['Commune_norm'].astype(str).str.startswith(ville_glob))
    group_ville = df_agg[mask]
    if group_ville.empty:
        continue
    key_glob = (ville_glob, dep_str)
    dico[key_glob] = {var: {} for var in VARIABLES_JSON}
    dico[key_glob]['population'] = {}
    dico[key_glob]['coordonnees'] = None  # une seule valeur (invariant par année)
    for annee in sorted(group_ville['Annee'].dropna().unique()):
        g = group_ville[group_ville['Annee'] == annee]
        m = g[g['Code_type_local'] == 1]
        a = g[g['Code_type_local'] == 2]
        year_str = str(int(annee))
        remplir_stats(dico[key_glob], g, m, a, year_str)
        if 'Nb_hab_com' in g.columns and len(g) > 0 and g['Nb_hab_com'].notna().any():
            pop_ville = g.groupby('Commune_norm', observed=True)['Nb_hab_com'].first().sum()
            dico[key_glob]['population'][year_str] = int(pop_ville) if pd.notna(pop_ville) else None
        else:
            dico[key_glob]['population'][year_str] = None
        if dico[key_glob]['coordonnees'] is None:
            lat = safe_float(g.groupby('Commune_norm', observed=True)['latitude_mairie'].first().mean()) if 'latitude_mairie' in g.columns and len(g) > 0 and g['latitude_mairie'].notna().any() else None
            lon = safe_float(g.groupby('Commune_norm', observed=True)['longitude_mairie'].first().mean()) if 'longitude_mairie' in g.columns and len(g) > 0 and g['longitude_mairie'].notna().any() else None
            dico[key_glob]['coordonnees'] = { 'latitude_mairie': lat, 'longitude_mairie': lon }

# 5bis) Segment_Commune (10 segments), Prix_med_groupe_pop, Ecart_pct, Quartile, évolution population
# Bins population (10 segments) :
#   Très rural (0-500) | Rural (500-2k) | Petite ville (2k-5k) | Ville petite (5k-10k) | Ville moyenne- (10k-20k)
#   Ville moyenne (20k-50k) | Grande ville (50k-100k) | Très grande ville (100k-200k) | Métropole (200k-500k) | Grande métropole (500k+)
bins_pop = [0, 500, 2000, 5000, 10000, 20000, 50000, 100000, 200000, 500000, float('inf')]
labels_pop = ['Très rural', 'Rural', 'Petite ville', 'Ville petite', 'Ville moyenne-', 'Ville moyenne', 'Grande ville', 'Très grande ville', 'Métropole', 'Grande métropole']

rows = []
for (commune, dep), data in dico.items():
    for year_str, pop in data.get('population', {}).items():
        p2med = data.get('Prix_m2_med', {}).get(year_str) if isinstance(data.get('Prix_m2_med'), dict) else None
        if pop is not None and p2med is not None:
            rows.append({'commune': commune, 'dep': dep, 'year': year_str, 'population': pop, 'Prix_m2_med': p2med})

if rows:
    df_seg = pd.DataFrame(rows)
    df_seg['Segment_Commune'] = pd.cut(df_seg['population'], bins=bins_pop, labels=labels_pop)
    df_seg['Prix_med_groupe_pop'] = df_seg.groupby(['Segment_Commune', 'year'], observed=False)['Prix_m2_med'].transform('median')
    df_seg['Ecart_pct_prix_m2_vs_groupe'] = np.where(df_seg['Prix_med_groupe_pop'] > 0, ((df_seg['Prix_m2_med'] - df_seg['Prix_med_groupe_pop']) / df_seg['Prix_med_groupe_pop'] * 100).round(2), np.nan)
    def quartile_in_group(s):
        return pd.qcut(s.rank(method='first'), q=4, labels=[1, 2, 3, 4], duplicates='drop')
    df_seg['Quartile_prix_m2_dans_segment'] = df_seg.groupby(['Segment_Commune', 'year'], observed=False)['Prix_m2_med'].transform(quartile_in_group)
    for row in df_seg.itertuples(index=False):
        key = (row.commune, row.dep)
        if key not in dico:
            continue
        y = str(row.year)
        dico[key]['Segment_Commune'] = str(row.Segment_Commune)  # une seule valeur (invariant par année)
        dico[key].setdefault('Prix_med_groupe_pop', {})[y] = safe_float(row.Prix_med_groupe_pop)
        dico[key].setdefault('Ecart_pct_prix_m2_vs_groupe', {})[y] = safe_float(row.Ecart_pct_prix_m2_vs_groupe) if pd.notna(row.Ecart_pct_prix_m2_vs_groupe) else None
        q = row.Quartile_prix_m2_dans_segment
        try:
            dico[key]['Quartile_prix_m2_dans_segment'] = int(q) if pd.notna(q) else None  # une seule valeur
        except (TypeError, ValueError):
            dico[key]['Quartile_prix_m2_dans_segment'] = None
    print(f"Segment_Commune (10 bins), Prix_med_groupe_pop, Ecart_pct, Quartile : {len(df_seg)} (commune, année).")
else:
    print("Aucune donnée population/Prix_m2_med : variables segment non calculées.")

# Évolution de la population (sur la période + variation annuelle)
for key in dico:
    data = dico[key]
    pop_series = data.get('population') or {}
    if not pop_series or not isinstance(pop_series, dict):
        data['evolution_population'] = None
        data['variation_annuelle_population'] = {}
        continue
    years = sorted([int(y) for y in pop_series if pop_series[y] is not None])
    if len(years) < 2:
        data['evolution_population'] = None
        data['variation_annuelle_population'] = {str(y): None for y in years}
        continue
    pop_debut = pop_series[str(years[0])]
    pop_fin = pop_series[str(years[-1])]
    pct_evol = round((pop_fin - pop_debut) / pop_debut * 100, 2) if pop_debut and pop_debut > 0 else None
    data['evolution_population'] = {'debut_annee': years[0], 'fin_annee': years[-1], 'pct': pct_evol}
    var_ann = {str(years[0]): None}
    for i in range(1, len(years)):
        p_prev, p_curr = pop_series[str(years[i-1])], pop_series[str(years[i])]
        var_ann[str(years[i])] = round((p_curr - p_prev) / p_prev * 100, 2) if p_prev and p_prev > 0 else None
    data['variation_annuelle_population'] = var_ann
print("evolution_population et variation_annuelle_population remplis.")

for key in dico:
    data = dico[key]
    if 'Prix_m2_med' not in data or not data['Prix_m2_med']:
        data['evolution_prix_m2'] = None
        data['tendance'] = None
        data['variation_annuelle_prix_m2'] = {}
        continue
    series = data['Prix_m2_med']
    annees = sorted([int(y) for y in series.keys() if series[y] is not None])
    if len(annees) < 2:
        data['evolution_prix_m2'] = None
        data['tendance'] = 'Données insuffisantes'
        data['variation_annuelle_prix_m2'] = {str(y): None for y in annees}
        continue
    annee_debut, annee_fin = annees[0], annees[-1]
    prix_debut = series[str(annee_debut)]
    prix_fin = series[str(annee_fin)]
    if prix_debut and prix_debut > 0:
        pct = round((prix_fin - prix_debut) / prix_debut * 100, 2)
    else:
        pct = None
    data['evolution_prix_m2'] = {
        'debut_annee': annee_debut,
        'fin_annee': annee_fin,
        'pct': pct
    }
    if pct is None:
        data['tendance'] = 'Données insuffisantes'
    elif pct > 10.0:
        data['tendance'] = 'Très forte hausse'
    elif pct > 2.0 :
        data['tendance'] = 'Hausse'
    elif pct < -10.0 :
        data['tendance'] = 'Très forte baisse'
    elif pct < -2.0 :
        data['tendance'] = 'Baisse'
    else:
        data['tendance'] = 'Stable'
    # Variation annuelle : pour chaque année, % par rapport à l'année précédente
    var_annuelle = {}
    for i, an in enumerate(annees):
        if i == 0:
            var_annuelle[str(an)] = None
        else:
            p_prev = series[str(annees[i-1])]
            p_curr = series[str(an)]
            if p_prev and p_prev > 0 and p_curr is not None:
                var_annuelle[str(an)] = round((p_curr - p_prev) / p_prev * 100, 2)
            else:
                var_annuelle[str(an)] = None
    data['variation_annuelle_prix_m2'] = var_annuelle
    # Année où les prix ont le plus augmenté / le plus baissé
    var_valide = {y: v for y, v in var_annuelle.items() if v is not None}
    if var_valide:
        data['annee_plus_forte_hausse_prix'] = max(var_valide, key=var_valide.get)
        data['annee_plus_forte_baisse_prix'] = min(var_valide, key=var_valide.get)
    else:
        data['annee_plus_forte_hausse_prix'] = None
        data['annee_plus_forte_baisse_prix'] = None

# Indicateurs communs à toutes les villes (même sans Prix_m2_med)
for key in dico:
    data = dico[key]
    # Période des données disponibles
    if 'Nb_total_ventes' in data and data['Nb_total_ventes']:
        annees = sorted([int(y) for y in data['Nb_total_ventes'].keys()])
        data['periode_donnees'] = {'debut': annees[0], 'fin': annees[-1]}
    else:
        data['periode_donnees'] = None
    # Évolution du nombre de ventes (sur toute la période)
    if 'Nb_total_ventes' in data and data['Nb_total_ventes']:
        v = data['Nb_total_ventes']
        annees = sorted([int(y) for y in v.keys()])
        if len(annees) >= 2:
            n_debut, n_fin = v[str(annees[0])], v[str(annees[-1])]
            pct_ventes = round((n_fin - n_debut) / n_debut * 100, 2) if n_debut and n_debut > 0 else None
            data['evolution_ventes'] = {'debut_annee': annees[0], 'fin_annee': annees[-1], 'pct': pct_ventes}
            # Variation annuelle des ventes (%)
            var_v = {str(annees[0]): None}
            for i in range(1, len(annees)):
                n_prev, n_curr = v[str(annees[i-1])], v[str(annees[i])]
                var_v[str(annees[i])] = round((n_curr - n_prev) / n_prev * 100, 2) if n_prev and n_prev > 0 else None
            data['variation_annuelle_ventes'] = var_v
        else:
            data['evolution_ventes'] = None
            data['variation_annuelle_ventes'] = {str(annees[0]): None} if annees else {}
    else:
        data['evolution_ventes'] = None
        data['variation_annuelle_ventes'] = {}

    # Années forte hausse/baisse si pas déjà rempli (ville sans Prix_m2_med)
    if 'annee_plus_forte_hausse_prix' not in data:
        data['annee_plus_forte_hausse_prix'] = None
        data['annee_plus_forte_baisse_prix'] = None

dico[('ORLEANS', '45')]

def to_json_serializable(obj):
    if isinstance(obj, dict):
        return {str(k): to_json_serializable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [to_json_serializable(x) for x in obj]
    if isinstance(obj, (int, float)) and isinstance(obj, float) and obj != obj:  # NaN
        return None
    if isinstance(obj, (np.integer, np.floating)):
        return float(obj) if not (isinstance(obj, float) and np.isnan(obj)) else None
    return obj

dico_json = {}
for (commune, dep), data in dico.items():
    key = f"{commune}|{dep}"
    dico_json[key] = to_json_serializable(data)

# Chemin à adapter si besoin (Colab vs local)
out_path = '/content/drive/MyDrive/Use Case/Projet 3/json_par_ville.json'
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(dico_json, f, ensure_ascii=False, indent=1)
print("JSON enregistré :", out_path)